[global]
	usershare path = /var/lib/samba/usershares
	usershare max shares = 100
	usershare allow guests = yes
	usershare owner only = yes
	usershare prefix deny list = /etc, /dev, /sys
	usershare prefix allow list = /home, /srv, /mnt, /media
